spring:
  application:
    name: bankingapp-account-service
  datasource:
    url: jdbc:postgresql://db:5432/FSD_Training
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format_sql: true
  h2:
    console:
      enabled: true

# Server Port
server:
  port: 9093

# Eureka Client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

# Actuator Endpoints
management:
  endpoints:
    web:
      exposure:
        include: '*'